/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete;

import javax.swing.JOptionPane;

/**
 *
 * @author Azael
 */
public class implementacion extends javax.swing.JFrame {

    /**
     * Creates new form implementacion
     */
    public implementacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarPersonalizable1 = new paquete.MenuBarPersonalizable();
        menuFiguras = new javax.swing.JMenu();
        menuCuadrado = new javax.swing.JMenu();
        menuAreaCuadrado = new javax.swing.JMenuItem();
        menuPerimetroCuadrado = new javax.swing.JMenuItem();
        menuRectangulo = new javax.swing.JMenu();
        menuAreaRectangulo = new javax.swing.JMenuItem();
        menuPerimetroRectangulo = new javax.swing.JMenuItem();
        menuTriangulo = new javax.swing.JMenu();
        menuAreaTriangulo = new javax.swing.JMenuItem();
        menuPerimetroTriangulo = new javax.swing.JMenuItem();
        menuPentagono = new javax.swing.JMenu();
        menuAreaPentagono = new javax.swing.JMenuItem();
        menuPerimetroPentagono = new javax.swing.JMenuItem();
        menuHexagono = new javax.swing.JMenu();
        menuAreaHexagono = new javax.swing.JMenuItem();
        menuPerimetroHexagono = new javax.swing.JMenuItem();
        menuCirculo = new javax.swing.JMenu();
        menuAreaCirculo = new javax.swing.JMenuItem();
        menuPerimetroCirculo = new javax.swing.JMenuItem();
        menuCerrar = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFiguras.setText("Figuras");

        menuCuadrado.setText("Cuadrado");

        menuAreaCuadrado.setText("Calcular Area");
        menuAreaCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAreaCuadradoActionPerformed(evt);
            }
        });
        menuCuadrado.add(menuAreaCuadrado);

        menuPerimetroCuadrado.setText("Calcular Perimetro");
        menuPerimetroCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPerimetroCuadradoActionPerformed(evt);
            }
        });
        menuCuadrado.add(menuPerimetroCuadrado);

        menuFiguras.add(menuCuadrado);

        menuRectangulo.setText("Rectangulo");

        menuAreaRectangulo.setText("Calcular Area");
        menuAreaRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAreaRectanguloActionPerformed(evt);
            }
        });
        menuRectangulo.add(menuAreaRectangulo);

        menuPerimetroRectangulo.setText("Calcular Perimetro");
        menuPerimetroRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPerimetroRectanguloActionPerformed(evt);
            }
        });
        menuRectangulo.add(menuPerimetroRectangulo);

        menuFiguras.add(menuRectangulo);

        menuTriangulo.setText("Triangulo");

        menuAreaTriangulo.setText("Calcular Area");
        menuAreaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAreaTrianguloActionPerformed(evt);
            }
        });
        menuTriangulo.add(menuAreaTriangulo);

        menuPerimetroTriangulo.setText("Calcular Perimetro");
        menuPerimetroTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPerimetroTrianguloActionPerformed(evt);
            }
        });
        menuTriangulo.add(menuPerimetroTriangulo);

        menuFiguras.add(menuTriangulo);

        menuPentagono.setText("Pentagono");

        menuAreaPentagono.setText("Calcular Area");
        menuAreaPentagono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAreaPentagonoActionPerformed(evt);
            }
        });
        menuPentagono.add(menuAreaPentagono);

        menuPerimetroPentagono.setText("Calcular Perimetro");
        menuPerimetroPentagono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPerimetroPentagonoActionPerformed(evt);
            }
        });
        menuPentagono.add(menuPerimetroPentagono);

        menuFiguras.add(menuPentagono);

        menuHexagono.setText("Hexagono");

        menuAreaHexagono.setText("Calcular Area");
        menuAreaHexagono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAreaHexagonoActionPerformed(evt);
            }
        });
        menuHexagono.add(menuAreaHexagono);

        menuPerimetroHexagono.setText("Calcular Perimetro");
        menuPerimetroHexagono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPerimetroHexagonoActionPerformed(evt);
            }
        });
        menuHexagono.add(menuPerimetroHexagono);

        menuFiguras.add(menuHexagono);

        menuCirculo.setText("Circulo");

        menuAreaCirculo.setText("Calcular Area");
        menuAreaCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAreaCirculoActionPerformed(evt);
            }
        });
        menuCirculo.add(menuAreaCirculo);

        menuPerimetroCirculo.setText("Calcular Perimetro");
        menuPerimetroCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPerimetroCirculoActionPerformed(evt);
            }
        });
        menuCirculo.add(menuPerimetroCirculo);

        menuFiguras.add(menuCirculo);

        menuBarPersonalizable1.add(menuFiguras);

        menuCerrar.setText("Cerrar");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuCerrar.add(menuSalir);

        menuBarPersonalizable1.add(menuCerrar);

        setJMenuBar(menuBarPersonalizable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAreaCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAreaCuadradoActionPerformed
        // TODO add your handling code here:try {
        try {
    double lado = Double.parseDouble(JOptionPane.showInputDialog(this, "Lado del cuadrado:"));
    double area = CalculadoraFiguras.areaCuadrado(lado);
    JOptionPane.showMessageDialog(this, "Área del cuadrado: " + area);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Entrada inválida.");
}
    }//GEN-LAST:event_menuAreaCuadradoActionPerformed

    private void menuPerimetroCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPerimetroCuadradoActionPerformed
        // TODO add your handling code here:
        try {
        double lado = Double.parseDouble(JOptionPane.showInputDialog(this, "Lado del cuadrado:"));
        double perimetro = CalculadoraFiguras.perimetroCuadrado(lado);
        JOptionPane.showMessageDialog(this, "Perímetro del cuadrado: " + perimetro);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida.");
    }
    }//GEN-LAST:event_menuPerimetroCuadradoActionPerformed

    private void menuAreaRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAreaRectanguloActionPerformed
        // TODO add your handling code here:
         try {
        double base = Double.parseDouble(JOptionPane.showInputDialog(this, "Base del rectángulo:"));
        double altura = Double.parseDouble(JOptionPane.showInputDialog(this, "Altura del rectángulo:"));
        double area = CalculadoraFiguras.areaRectangulo(base, altura);
        JOptionPane.showMessageDialog(this, "Área del rectángulo: " + area);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida.");
    }
    }//GEN-LAST:event_menuAreaRectanguloActionPerformed

    private void menuPerimetroRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPerimetroRectanguloActionPerformed
        // TODO add your handling code here:
        try {
        double base = Double.parseDouble(JOptionPane.showInputDialog(this, "Base del rectángulo:"));
        double altura = Double.parseDouble(JOptionPane.showInputDialog(this, "Altura del rectángulo:"));
        double perimetro = CalculadoraFiguras.perimetroRectangulo(base, altura);
        JOptionPane.showMessageDialog(this, "Perímetro del rectángulo: " + perimetro);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida.");
    }
    }//GEN-LAST:event_menuPerimetroRectanguloActionPerformed

    private void menuAreaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAreaTrianguloActionPerformed
        // TODO add your handling code here:
        try {
        double base = Double.parseDouble(JOptionPane.showInputDialog(this, "Base del triángulo:"));
        double altura = Double.parseDouble(JOptionPane.showInputDialog(this, "Altura del triángulo:"));
        double area = CalculadoraFiguras.areaTriangulo(base, altura);
        JOptionPane.showMessageDialog(this, "Área del triángulo: " + area);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida.");
    }
    }//GEN-LAST:event_menuAreaTrianguloActionPerformed

    private void menuPerimetroTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPerimetroTrianguloActionPerformed
        // TODO add your handling code here:
        try {
        double l1 = Double.parseDouble(JOptionPane.showInputDialog(this, "Lado 1:"));
        double l2 = Double.parseDouble(JOptionPane.showInputDialog(this, "Lado 2:"));
        double l3 = Double.parseDouble(JOptionPane.showInputDialog(this, "Lado 3:"));
        double perimetro = CalculadoraFiguras.perimetroTriangulo(l1, l2, l3);
        JOptionPane.showMessageDialog(this, "Perímetro del triángulo: " + perimetro);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida.");
    }
    }//GEN-LAST:event_menuPerimetroTrianguloActionPerformed

    private void menuAreaPentagonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAreaPentagonoActionPerformed
        // TODO add your handling code here:
        try {
        double lado = Double.parseDouble(JOptionPane.showInputDialog(this, "Lado del pentágono:"));
        double apotema = Double.parseDouble(JOptionPane.showInputDialog(this, "Apotema:"));
        double area = CalculadoraFiguras.areaPoligonoRegular(5, lado, apotema);
        JOptionPane.showMessageDialog(this, "Área del pentágono: " + area);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida.");
    }
    }//GEN-LAST:event_menuAreaPentagonoActionPerformed

    private void menuPerimetroPentagonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPerimetroPentagonoActionPerformed
        // TODO add your handling code here:
        try {
        double lado = Double.parseDouble(JOptionPane.showInputDialog(this, "Lado del pentágono:"));
        double perimetro = CalculadoraFiguras.perimetroPoligonoRegular(5, lado);
        JOptionPane.showMessageDialog(this, "Perímetro del pentágono: " + perimetro);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida.");
    }
    }//GEN-LAST:event_menuPerimetroPentagonoActionPerformed

    private void menuAreaHexagonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAreaHexagonoActionPerformed
        // TODO add your handling code here:
        try {
        double lado = Double.parseDouble(JOptionPane.showInputDialog(this, "Lado del hexágono:"));
        double apotema = Double.parseDouble(JOptionPane.showInputDialog(this, "Apotema:"));
        double area = CalculadoraFiguras.areaPoligonoRegular(6, lado, apotema);
        JOptionPane.showMessageDialog(this, "Área del hexágono: " + area);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida.");
    }
    }//GEN-LAST:event_menuAreaHexagonoActionPerformed

    private void menuPerimetroHexagonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPerimetroHexagonoActionPerformed
        // TODO add your handling code here:
        try {
        double lado = Double.parseDouble(JOptionPane.showInputDialog(this, "Lado del hexágono:"));
        double perimetro = CalculadoraFiguras.perimetroPoligonoRegular(6, lado);
        JOptionPane.showMessageDialog(this, "Perímetro del hexágono: " + perimetro);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida.");
    }
    }//GEN-LAST:event_menuPerimetroHexagonoActionPerformed

    private void menuAreaCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAreaCirculoActionPerformed
        // TODO add your handling code here:
        try {
        double radio = Double.parseDouble(JOptionPane.showInputDialog(this, "Radio del círculo:"));
        double area = CalculadoraFiguras.areaCirculo(radio);
        JOptionPane.showMessageDialog(this, "Área del círculo: " + area);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida.");
    }
    }//GEN-LAST:event_menuAreaCirculoActionPerformed

    private void menuPerimetroCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPerimetroCirculoActionPerformed
        // TODO add your handling code here:
        try {
        double radio = Double.parseDouble(JOptionPane.showInputDialog(this, "Radio del círculo:"));
        double perimetro = CalculadoraFiguras.perimetroCirculo(radio);
        JOptionPane.showMessageDialog(this, "Perímetro del círculo: " + perimetro);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida.");
    }
    }//GEN-LAST:event_menuPerimetroCirculoActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(implementacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(implementacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(implementacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(implementacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new implementacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem menuAreaCirculo;
    private javax.swing.JMenuItem menuAreaCuadrado;
    private javax.swing.JMenuItem menuAreaHexagono;
    private javax.swing.JMenuItem menuAreaPentagono;
    private javax.swing.JMenuItem menuAreaRectangulo;
    private javax.swing.JMenuItem menuAreaTriangulo;
    private paquete.MenuBarPersonalizable menuBarPersonalizable1;
    private javax.swing.JMenu menuCerrar;
    private javax.swing.JMenu menuCirculo;
    private javax.swing.JMenu menuCuadrado;
    private javax.swing.JMenu menuFiguras;
    private javax.swing.JMenu menuHexagono;
    private javax.swing.JMenu menuPentagono;
    private javax.swing.JMenuItem menuPerimetroCirculo;
    private javax.swing.JMenuItem menuPerimetroCuadrado;
    private javax.swing.JMenuItem menuPerimetroHexagono;
    private javax.swing.JMenuItem menuPerimetroPentagono;
    private javax.swing.JMenuItem menuPerimetroRectangulo;
    private javax.swing.JMenuItem menuPerimetroTriangulo;
    private javax.swing.JMenu menuRectangulo;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenu menuTriangulo;
    // End of variables declaration//GEN-END:variables
}
